### ISSUE TITLE
Provider Review

### ISSUE THREAD

**Issue by mbfrahry** [hedvig/terraform-provider-hedvig#4]
Hello! My name is Matthew and I'm on the Terraform team at Hashicorp. I've taken a look through the provider and things look good but there are some problem areas and repository cleanup I'd like to address before we move forward with moving it under our github organization. The ones towards the top of the list are must haves while moving down the list tend to be more suggestions for improvement. Also, if I called out a specific area, please go through the other resources to confirm that my feedback can't also be addressed there. This list is not set in stone and we can discuss any areas that don't make sense or you'd like additional feedback on.

- [x] There are some files that are specific to developing this provider. These can be removed [USERGUIDE.txt](https://github.com/hedvig/terraform-provider-hedvig/blob/master/USERGUIDE.txt) and [README.txt](https://github.com/hedvig/terraform-provider-hedvig/blob/master/README.txt)

- [x] [README.md](https://github.com/hedvig/terraform-provider-hedvig/blob/master/README.md) should be fleshed out to look like other providers. I'd look at our other major clouds [aws](https://github.com/hedvig/terraform-provider-hedvig/blob/master/USERGUIDE.txt), [azure](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/README.md), and/or [google](https://github.com/terraform-providers/terraform-provider-google/blob/master/README.md) for the proper format.

- [x] The [id](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/provider.go#L111) of a resource should be set after all the errors have been checked. 

- [x] The id also needs to be the amalgamation of every attribute needed to retrieve the resource. Then when you call read or update, you'll parse that id and use those values to read or delete the resource. Values tend to be retrieved from the config file over the statefile. This is especially true when you are doing a `d.Get` and values may have been changed in the configuration file between runs that would affect how a resource is retrieved/modified.

- [x] If a resource cannot be found(404) in the [read function](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/resource_lun.go#L92), we should do a d.SetId("") to remove it from the statefile. You also wouldn't need to return an error then. Terraform will just treat it as a resource that never existed and try and create it.

- [x] Panicking inside of Terraform represents a major issue and should be prevented whenever possible. One of the adverse side effects of panicking is losing your statefile which is a worst case scenario for most users of Terraform. There are a couple of [places](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/resource_access.go#L120) you are using an array and these should be length checked to ensure the index exists before you access it to prevent a panic. 

- [x] It doesn't look like every [attribute](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/resource_lun.go#L106) is being set in the read function. Is this information missing from the [response](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/provider.go#L111)? If so, can it be added in?

- [x] From reading your code it looks like the majority of your [update functions](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/resource_access.go#L126) delete the resource and recreate it. This can be done in a different way by adding `ForceNew: true` to any attribute that requires a recreation of the resource instead of just an Update. I suggest you go through and add that to the majority of your attributes and remove the update tags. 

- [x] For [vdisk](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/resource_vdisk.go) you want to add `ForceNew: true` to every attribute but `size`. 

- [x] It looks like [errors](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/provider.go#L111) are just being logged and never returned. Is there a reason for that? I'd suggest returning errors whenever they are encountered. 

- [x] The provider authentication attributes should be pulled in from the environment. This can be done by adding `DefaultFunc: schema.EnvDefaultFunc("ENV_NAME", ""),` to the attribute declaration. 

- [x] [template.erb](https://github.com/hedvig/terraform-provider-hedvig/blob/master/website/template.erb) should be renamed to hedvig.erb. This is for ingesting your documentation into our website. 

- [x] In the [documentation](https://github.com/hedvig/terraform-provider-hedvig/blame/master/website/docs/r/access.html.markdown#L39) you are telling people to use specific values. Inside of the resource config, we can confirm that the user is using those values with 
```
ValidateFunc: validation.StringInSlice([]string{
    "host",
    "ip",
    "iqn"
}, true),
```

- [x] There are a couple of [areas](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/resource_access.go#L70) where you are missing the type conversion for a d.Get(""). Please go through and add .(string), or .(whatever_the_type_is) to any d.Get("") call.

- [ ] [testAccCheckHedvigAccessExists](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/resource_access_test.go#L96) is just checking the resource exists in the state but it should also be checking whether or not it gets returned from the api.

- [x] We also want to check that the resource actually gets destroyed in the test by adding `CheckDestroy: testAccCheckHedvigAccessCheckDestoyed()` to the test. `testAccCheckHedvigAccessCheckDestroyed()` looks similar to `testAccCheckHedvigAccessExists` but confirms that the resource does not get returned from the api.

- [x] [This](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/resource_access_test.go#L14) is added to the top of every test file but it's not called anywhere. Can you remove this or is it needed? 

- [x] I also want to confirm that [result](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/resource_mount.go#L103) is actually the controller name and not the mount name. It's confusing from looking at the [json respose](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/resource_mount.go#L14)

- [ ] The size of the [vdisk](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/resource_vdisk_test.go#L20) should be confirmed in the test and an additional test step should be added to update that size and confirm it was updated. 

- [x] Most of [examples/config.tf](https://github.com/hedvig/terraform-provider-hedvig/blob/master/examples/config.tf) is commented out. Do you plan on using this or can it be removed?

- [x] There are some comments that are [old](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/provider.go#L51) or [outdated](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/resource_lun.go#L74) that should be updated or removed. Do you mind going through and checking that all the comments in this provider are necessary. 

- [ ] There is quite a [bit](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/provider.go#L95) of [code](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/provider.go#L27) that would be better suited towards being in an sdk. Have you thought about separating out the api calls and setup into it's own sdk?

**Comment by katrinahayes** [comment]
Hello Matthew,
Pleased to meet you! In the course of working on this, I'm seeing a large error that states "diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue." However, it refers to specifics of the resource in development. Could I ask you guys for help? Or is this just boilerplate error messaging?

Either way, thanks and I look forward to working with you.

Katrina

**Comment by mbfrahry** [comment]
Hey Katrina. I received this notification from github but I don't see the comment here.
```
Hello Matthew,
Pleased to meet you! In the course of working on this, I'm seeing a large error that states "diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue." However, it refers to specifics of the resource in development. Could I ask you guys for help? Or is this just boilerplate error messaging?

Either way, thanks and I look forward to working with you.

Katrina
```

I'm happy to help but I'll need a bit more information from you about the full error message. This error you're seeing about it being a bug in Terraform is slightly misleading as it is a bug in Terraform but more likely than not from somewhere in the provider code. It's basically saying that the output it expects doesn't match what it received. I'll have to see the full error message to help more though.

**Comment by katrinahayes** [comment]
Hello Matthew,
Thanks for reaching out! I took the comment down because I realized it was premature, and the issue did end up being caused by our set-up, so it’s been solved now.

That said, I will have some questions for you soon!

Thank you,

Katrina

**Comment by katrinahayes** [comment]
Hello Matthew,
I have a question about ForceNew. When I tried to add it to the various fields in Vdisk, it returned errors saying that ForceNew is incompatible with the Required tag. Is this the case? If so, how do you recommend I go forward with using the ForceNew tag with the various resources here?

Thank you,
Katrina

**Comment by mbfrahry** [comment]
Hey Katrina, do you happen to have a branch where I can view how you're using the `ForceNew: true` tag? That'll be easiest for me to see if it's an implementation issue or a bug with Terraform. Thank you!

**Comment by katrinahayes** [comment]
Hello Matthew,
The "review" branch currently generates this error when running "terraform apply":

* resource hedvig_mount: All fields are ForceNew or Computed w/out Optional, Update is superfluous

Thanks!

**Comment by mbfrahry** [comment]
Thank you! So with that one, the error is saying that you don't need [Update](https://github.com/hedvig/terraform-provider-hedvig/blob/a94d1dd4438eb1ae83d32a989d52683bb9126359/hedvig/resource_mount.go#L23) because if ever a value changes , the resource will just be recreated because every value is `ForceNew: true`. Try removing the line linked above and let me know if that works.

**Comment by katrinahayes** [comment]
Hello Matthew,
Thank you! That fixed it right up. I have some questions about the other tasks.

First, The id also needs to be the amalgamation of every attribute needed to retrieve the resource. I thought I already had it doing that? I took every attribute needed to make the ID unique and made that the ID.

Second, that the provider authentication attributes should come from the environment. Where does that go?

Similarly, there are specific values we're telling people to use in the documentation, that should be confirmed in the resource config. Where does that go?

**Comment by katrinahayes** [comment]
Hello Matthew,
Thank you! That fixed it right up. I have some questions about the other tasks.

First, The id also needs to be the amalgamation of every attribute needed to retrieve the resource. I thought I already had it doing that? I took every attribute needed to make the ID unique and made that the ID.

Second, that the provider authentication attributes should come from the environment. Where does that go?

Similarly, there are specific values we're telling people to use in the documentation, that should be confirmed in the resource config. Where does that go?

Thank you,
Katrina

**Comment by mbfrahry** [comment]
1. It looks like you've almost got the id generation correct but let's take a look [here](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/resource_lun.go#L154). The id is set using to `d.SetId("lun-" + d.Get("vdisk").(string))`, but in the above link you are doing a get call on the controller as well. The id should be comprised of every attribute needed to identify the resource and then when accessing those variables you need to parse that id and not do a `d.Get` call in either the Read or the Delete. The way you're currently doing it can cause issues if the user changes their configuration file and it might cause issues with a corresponding read or delete. For example, a user could have created a resource that is `vdisk = "vdiskA"` and then for whatever reason they want `vdisk = "vdiskB"`. Now when they delete the resource, the way it's currently written will try to read or delete the resource related to "vdiskB" which doesn't exist. 

Also, if ever you add import support (this is highly recommended), the way Read is currently implemented will not work because d.Get("vdisk") doesn't exist yet. If we ship this way and then add this feature in later, we will have to migrate users over to the new id generation and it most likely will cause headaches for you as a maintainer. Sorry for the rant and I hope this makes sense! 

2) You can grab add `DefaultFunc: schema.EnvDefaultFunc("ENV_NAME", ""),` to the attribute declaration. And it'll look like 
```
"username": &schema.Schema{
	Type:     schema.TypeString,
	Required: true,
        DefaultFunc: schema.EnvDefaultFunc("ENV_NAME", ""),
},
```
You can check out what the method is doing [here](https://godoc.org/github.com/hashicorp/terraform/helper/schema#EnvDefaultFunc)

3) Just like with environment authentication information, the validation information will go in the same place and will look like
```
"type": &schema.Schema{
	Type:     schema.TypeString,
	Required: true,
        ValidateFunc: validation.StringInSlice([]string{
                "host",
                "ip",
               "iqn"
        }, true),
},
```

**Comment by katrinahayes** [comment]
Ah, okay, thanks. So to be clear, any attribute that can be called with d.Set("foo") needs to be a part of the id then?

**Comment by katrinahayes** [comment]
Ah, okay, thanks. So any attribute that can be called with d.Set("foo") needs to be a part of the id then?

**Comment by mbfrahry** [comment]
Not quite. Any attribute that is needed when either reading or deleting the resource needs to be in the id. For example when you try and [delete access](https://github.com/hedvig/terraform-provider-hedvig/blob/master/hedvig/resource_access.go#L178), you are grabbing `vdisk`, `host`, and `address`. So those attributes should comprise the id, then when you need those values, you'll parse the id and use those instead of calling d.Get("foo")

**Comment by katrinahayes** [comment]
Hello Matthew,
I know there are still some tasks outstanding, but if you have the time could you take a look at the "review" branch and let us know how it looks? That's where I've been putting these updates and I'm curious how we're measuring up.

Thank you!
Katrina

**Comment by katrinahayes** [comment]
Hello Matthew,
Regarding the question about whether a result is a controller or a mount, it appears to be a controller. Here is the full curl result from our API: 

{
"requestId": "2F09ECB1-2F52-DC64-8933-49F85D50C8F3", "result": [
        "hedvigvip1.hedviginc.com"
    ],
    "status": "ok",
    "type": "ListExportedTargets"
}

A vip is a controller.

**Comment by mbfrahry** [comment]
Hey @katrinahayes. Taking a look over the review branch and you're on the right path.

- [x] [Here](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-a90839423c528c4d79ab9786c1f2a3b8R106) though we want to move away from calling `d.Get` in the Read function. You should parse `d.Id()` and use those values to obtain the resource. 

- [x] [This](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-a90839423c528c4d79ab9786c1f2a3b8R131) isn't the most helpful error message. As a user, I don't know what array is or why Terraform is failing here. I'd consider elaborating on what exactly is going on here.

- [x] [This function](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-a04ab625eb9fc69f5571ee0ea742e2e3R107) should try and get the resource from the api and make sure that it doesn't exist. 

- [x] With [these checks](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-19bfdf57b9a0b2acbf2bbb172f1256d4R96) we should also log that Terraform couldn't find the resource and that it's removing it from state. That should look something like
```
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_lb.go#L321
```

- [x] Also with the above 404 check, we don't need to error out if we can't find the resource. Terraform's natural workflow will just try and recreate the resource that isn't in the statefile

**Comment by mbfrahry** [comment]
For 
```
Hello Matthew,
Regarding the question about whether a result is a controller or a mount, it appears to be a controller. Here is the full curl result from our API:

{
"requestId": "2F09ECB1-2F52-DC64-8933-49F85D50C8F3", "result": [
"hedvigvip1.hedviginc.com"
],
"status": "ok",
"type": "ListExportedTargets"
}

A vip is a controller.
```
That sounds good to me! I was just confirming as the naming was a little difficult to wrap my head around.

**Comment by katrinahayes** [comment]
> Hey @katrinahayes. Taking a look over the review branch and you're on the right path.
> 
> * [ ]  [Here](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-a90839423c528c4d79ab9786c1f2a3b8R106) though we want to move away from calling `d.Get` in the Read function. You should parse `d.Id()` and use those values to obtain the resource.
> * [ ]  [This](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-a90839423c528c4d79ab9786c1f2a3b8R131) isn't the most helpful error message. As a user, I don't know what array is or why Terraform is failing here. I'd consider elaborating on what exactly is going on here.
> * [ ]  [This function](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-a04ab625eb9fc69f5571ee0ea742e2e3R107) should try and get the resource from the api and make sure that it doesn't exist.
> * [ ]  With [these checks](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-19bfdf57b9a0b2acbf2bbb172f1256d4R96) we should also log that Terraform couldn't find the resource and that it's removing it from state. That should look something like
> 
> ```
> https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_lb.go#L321
> ```
> * [ ]  Also with the above 404 check, we don't need to error out if we can't find the resource. Terraform's natural workflow will just try and recreate the resource that isn't in the statefile

**Comment by katrinahayes** [comment]
Hello Matthew,
I seem to have done something to contaminate the review branch. No matter what I do (terraform apply after go build, terraform init, terraform plan; I've also tried going back several git commits), I keep getting the same double error: "* hedvig_mount.my-mount: hedvig_mount.my-mount: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue." That's the first part; the second part is: "* hedvig_lun.my-lun3: hedvig_lun.my-lun3: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue." There is also a large paragraph associated with each saying to include the following in my report, which I can attach if helpful. I think the key though is "Mismatch reason: attribute mismatch: vdisk." Any thoughts on how to fix this?

Thank you!

**Comment by katrinahayes** [comment]
Hello Matthew,
Thanks for all your help so far! I'm getting started on addressing the second batch of issues you've highlighted.

I seem to have done something to contaminate the review branch. No matter what I do (terraform apply after go build and terraform destroy, terraform init, terraform plan; I've also tried going back several git commits), I keep getting the same double error: "* hedvig_mount.my-mount: hedvig_mount.my-mount: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue." That's the first part; the second part is: "* hedvig_lun.my-lun3: hedvig_lun.my-lun3: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue." There is also a large paragraph associated with each saying to include the following in my report, which I can attach if helpful. I think the key though is "Mismatch reason: attribute mismatch: vdisk." Any thoughts on how to fix this?

Thank you!

**Comment by katrinahayes** [comment]
Hello Matthew,
I started a new branch off of the original master, and somehow that made things worse. I'm now getting "!!! TERRAFORM CRASH !!!" and a crash log that I've attached. I don't know what I'm doing wrong?
[terraform_181113.txt](https://github.com/hedvig/terraform-provider-hedvig/files/2578644/terraform_181113.txt)

Thanks!

**Comment by mbfrahry** [comment]
Oh no, that's no good. So for the mismatch error, it's an issue where the config and states refuse to match. I'd check to make sure that you are setting the variables correctly. For the crash, it looks like that txt file isn't showing the full state. What you should look for is a panic and post everything underneath that. This might be a variety of things though. Most of the time it is either a miscasting an attribute (ie. casting a string to an int) or trying to access something nil or array out of bounds. I can't know for certain though without the panic message.

Also posting the full attribute mismatch error message would be helpful

**Comment by katrinahayes** [comment]
I found the panic; the document was copy and pasted and I didn't capture everything from my terminal. I've attached the full version now.
[terraform_181113.txt](https://github.com/hedvig/terraform-provider-hedvig/files/2578931/terraform_181113.txt)

Thanks for the pointers!

**Comment by mbfrahry** [comment]
Found it! Looks like it's 
`2018-11-13T18:06:11.394-0800 [DEBUG] plugin.terraform-provider-hedvig: panic: runtime error: index out of range`. More specifically, it's from this line `2018-11-13T18:06:11.394-0800 [DEBUG] plugin.terraform-provider-hedvig:  /home/katrina/go/src/terraform-provider-hedvig/hedvig/resource_lun.go:107 +0x60b`. Anytime you get a panic, there is normally a stack trace that you gets spit out towards the end of the run. You can use that to figure out where exactly Terraform is panicking. It's towards the end of your file you posted.

```
2018-11-13T18:06:11.394-0800 [DEBUG] plugin.terraform-provider-hedvig: panic: runtime error: index out of range
2018-11-13T18:06:11.394-0800 [DEBUG] plugin.terraform-provider-hedvig:
2018-11-13T18:06:11.394-0800 [DEBUG] plugin.terraform-provider-hedvig: goroutine 60 [running]:
2018-11-13T18:06:11.394-0800 [DEBUG] plugin.terraform-provider-hedvig: terraform-provider-hedvig/hedvig.resourceLunRead(0xc0001f2070, 0xc35500, 0xc0003d6cc0, 0xc0001f2070, 0x0)
2018-11-13T18:06:11.394-0800 [DEBUG] plugin.terraform-provider-hedvig:  /home/katrina/go/src/terraform-provider-hedvig/hedvig/resource_lun.go:107 +0x60b
2018-11-13T18:06:11.394-0800 [DEBUG] plugin.terraform-provider-hedvig: terraform-provider-hedvig/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc000398b60, 0xc0001aa190, 0xc35500, 0xc0003d6cc0, 0xc0003974e0, 0x4c2a01, 0xc36c00)
2018-11-13T18:06:11.394-0800 [DEBUG] plugin.terraform-provider-hedvig:  /home/katrina/go/src/terraform-provider-hedvig/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:352 +0x160
2018-11-13T18:06:11.394-0800 [DEBUG] plugin.terraform-provider-hedvig: terraform-provider-hedvig/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc000398cb0, 0xc0001aa140, 0xc0001aa190, 0xc000432000, 0x0, 0x7f6639176b00)
2018-11-13T18:06:11.394-0800 [DEBUG] plugin.terraform-provider-hedvig:  /home/katrina/go/src/terraform-provider-hedvig/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x92
2018-11-13T18:06:11.394-0800 [DEBUG] plugin.terraform-provider-hedvig: terraform-provider-hedvig/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc000190ca0, 0xc00018a460, 0xc00018a600, 0x0, 0x0)
2018-11-13T18:06:11.394-0800 [DEBUG] plugin.terraform-provider-hedvig:  /home/katrina/go/src/terraform-provider-hedvig/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-11-13T18:06:11.394-0800 [DEBUG] plugin.terraform-provider-hedvig: reflect.Value.call(0xc00009ee40, 0xc00018e3c0, 0x13, 0xdae9f6, 0x4, 0xc000568f18, 0x3, 0x3, 0xc000194800, 0xc00039c100, ...)
2018-11-13T18:06:11.395-0800 [DEBUG] plugin.terraform-provider-hedvig:  /opt/go1.11.1.linux-amd64/src/reflect/value.go:447 +0x449
2018-11-13T18:06:11.395-0800 [DEBUG] plugin.terraform-provider-hedvig: reflect.Value.Call(0xc00009ee40, 0xc00018e3c0, 0x13, 0xc0001a0718, 0x3, 0x3, 0x4b00000023, 0x1, 0x1000000010000)
2018-11-13T18:06:11.395-0800 [DEBUG] plugin.terraform-provider-hedvig:  /opt/go1.11.1.linux-amd64/src/reflect/value.go:308 +0xa4
2018-11-13T18:06:11.395-0800 [DEBUG] plugin.terraform-provider-hedvig: net/rpc.(*service).call(0xc000195340, 0xc00039a5a0, 0xc0001886f0, 0xc000188700, 0xc0003ac780, 0xc000191160, 0xc36bc0, 0xc00018a460, 0x16, 0xc36c00, ...)
2018-11-13T18:06:11.395-0800 [DEBUG] plugin.terraform-provider-hedvig:  /opt/go1.11.1.linux-amd64/src/net/rpc/server.go:384 +0x14e
2018-11-13T18:06:11.395-0800 [DEBUG] plugin.terraform-provider-hedvig: created by net/rpc.(*Server).ServeCodec
2018-11-13T18:06:11.395-0800 [DEBUG] plugin.terraform-provider-hedvig:  /opt/go1.11.1.linux-amd64/src/net/rpc/server.go:481 +0x47e
2018/11/13 18:06:11 [ERROR] root: eval: *terraform.EvalRefresh, err: hedvig_lun.my-lun3: unexpected EOF
2018/11/13 18:06:11 [ERROR] root: eval: *terraform.EvalSequence, err: hedvig_lun.my-lun3: unexpected EOF
2018/11/13 18:06:11 [TRACE] [walkRefresh] Exiting eval tree: hedvig_lun.my-lun3
2018/11/13 18:06:11 [TRACE] dag/walk: upstream errored, not walking "hedvig_access.my-access3"
2018-11-13T18:06:11.397-0800 [DEBUG] plugin: plugin process exited: path=/usr1/home/katrina/go/src/terraform-provider-hedvig/terraform-provider-hedvig
2018/11/13 18:06:11 [TRACE] dag/walk: upstream errored, not walking "hedvig_access.my-access2"
2018/11/13 18:06:11 [TRACE] dag/walk: upstream errored, not walking "hedvig_access.my-access"
2018/11/13 18:06:11 [TRACE] dag/walk: upstream errored, not walking "provider.hedvig (close)"
2018/11/13 18:06:11 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-11-13T18:06:11.397-0800 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
```

**Comment by katrinahayes** [comment]
Hello Matthew,
I've finished addressing the second batch of issues you brought up. They're all committed in the "review" branch. If you want to start looking at them I'd be much obliged, but I still haven't figured out what's going on with the "!!! TERRAFORM CRASH !!!" so I haven't been able to test the last few changes myself.

Thank you,
Katrina

**Comment by katrinahayes** [comment]
Hello Matthew,
I cleared the bug by removing terraform.tfstate, terraform.tfstate.backup, and main.go. Everything looks to be working right now and the changes are all in place, so if you could take a look at the "review" branch that would be excellent!

Thank you,
Katrina

**Comment by mbfrahry** [comment]
Hey @katrinahayes. I see the issue now with the crash. It's around this [line](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-f63761920ada9245bfd74b5f9288e577R89). The id in the statefile hasn't migrated over to the new form you're using so the index you were trying to access [here](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-f63761920ada9245bfd74b5f9288e577R92) doesn't exist. Deleting the tfstate did fix the issue but we can't ask users to do that. Normally, we'd have to migrate a users statefile to the new version and that is a little more involved. Luckily, the provider isn't official yet so we don't have to worry about this but it's a good thing to be aware of next time we need to modify a users state. As an aside, any time we are checking a specific index in an array (ie. array[1]) we should check the length and return an error if the index doesn't exist. Panicking is a terrible thing to to do inside of Terraform because it can wipe a users statefile and they have to rebuild that statefile which is no fun/extremely difficult so we try and take precautions wherever we can. I'll get off my soapbox now and continue the review. 

- [x] One last thing [here](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-f63761920ada9245bfd74b5f9288e577R102) We should add `return nil` to escape this method and set anything since the resource doesn't exist.

- [x] We should remove any comments like [this](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-19bfdf57b9a0b2acbf2bbb172f1256d4R23)

- [ ] It looks like some of the attribute setting done in the [read](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-8d0b3c6d54bd478898ed5e6f11cf492cR135) is missing. Are those missing from the api? Any chance we can grab them from somewhere?

- [x] I'm not entirely sure what [this](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-37f7e8bf13776e3538ba62fc8c55dca0R64) is doing. If you're trying to check an actual vs. expected value, we have a pretty handy sdk method to use that would look like.
```
resource.TestCheckResourceAttr(resourceName, "attr_name", value),
```

- [x] It also looks like you deleted the `website/template.erb` but we can keep it as we need it for our website to correctly point to your docs

**Comment by mbfrahry** [comment]
I'd go ahead and merge after you take care of these and we can do one final pass of the provider and move forward with officializing this provider! Thanks for taking care of all of these asks as well!

**Comment by katrinahayes** [comment]
Hello Matthew,
We've made quite a few changes in the "review" branch, including addressing all of the tasks you provided in the second-to-last comment you made here. Could you go ahead and take a look?

Thank you!
Katrina

**Comment by katrinahayes** [comment]
Hello Matthew,
Have you had a chance to look at the review branch? We're hoping to hear from you soon.

Thank you!
Katrina

**Comment by mbfrahry** [comment]
Hey @katrinahayes, apologies for the delay. Looking through, the changes are on the right track. I left a few comments below but the main thing is that there are quite a few TODOs lying around and I was just looking for confirmation on if those were going to be addressed in this branch or for some future date

- [x] We can remove this [line](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-a90839423c528c4d79ab9786c1f2a3b8R222) as Terraform handles removing the id when the delete method finishes successfully. 

- [x] Is there a reason [checkDestroyed](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-a04ab625eb9fc69f5571ee0ea742e2e3R102) is commented out? It's definitely handy to have while running tests.

- [x] This [TODO](https://github.com/hedvig/terraform-provider-hedvig/compare/review#diff-f63761920ada9245bfd74b5f9288e577R137) around setting the id to "" when we encounter a non 200 is almost there but we really only want to remove it from state when we get back a 400 since we know it doesn't exist. Any other errors should be reported but we shouldn't remove that resource from state because Terraform still needs to manage it because it exists.

**Comment by katrinahayes** [comment]
Hello Matthew,
Thanks for your response! I'm glad to hear we're on the right track. Most of those TODOs we were hoping to address after the provider has been released, as they seemed non-critical.

The checkDestroy in resource_access_test.go isn't working properly, that's why it's commented out. We know the Destroy test is an important one, so we've also added it to the other resources and are working on them as well.

For some reason all the links in your latest comment go to the list of commits in the review branch rather than what seems intended. I figured out where the first two referred to, but I'm not sure where the TODO you're talking about is. Could you try re-linking it?

Thank you!

**Comment by katrinahayes** [comment]
Hello Matthew,
I've figured out how to get the CheckDestroy tests working, so those are now in all of our resource tests. I also found the TODO you were talking about and replaced it with a 404 error.

With that, I believe everything has been addressed? Are we ready to merge?

Thank you!

**Comment by katrinahayes** [comment]
Hello Matthew,
We're hoping to hear from you. Have you had a chance to look at our recent work?

Thank you!

**Comment by mbfrahry** [comment]
Hey @katrinahayes, your other resources are checking against `!= 200` while trying to read the resource. If you fix that up then I believe you'll be good to go! Thanks for taking time to address my feedback!

**Comment by katrinahayes** [comment]
Hello @mbfrahry,
I've updated the other files to check against 404 instead of 200. Let me know if we're good to go! And if so, what are the next steps I need to take.

Thank you!

**Comment by mbfrahry** [comment]
That looks good! Just make sure you log that you're removing it from state so people know why something doesn't' exist in the statefile anymore. Go ahead and merge after that and Chris will work out the rest.
